[Interface]
PrivateKey = QlGwP4fMp4nDBqtCssP5hjm0dA1Peb0jQchX/exEbwI=
Address = 10.50.0.1/24

[Peer]
PublicKey = 06TNsVdYdwTdqEz/MfXtoqPTkodRtP90FOTHkXevt3I=
Endpoint = 3.123.253.16:51820
AllowedIPs = 10.50.0.2/32
PersistentKeepalive = 25