[Interface]
PrivateKey = QlGwP4fMp4nDBqtCssP5hjm0dA1Peb0jQchX/exEbwI=
Address = 10.50.0.1/24

[Peer]
PublicKey = UPl33ubqvBCQ3Ymn2EidRDppOsnP6/HbuBB24mUm+Ts=
Endpoint = 51.102.241.137:51820
AllowedIPs = 10.50.0.2/32
PersistentKeepalive = 25