function money(amount, currency = 'USD') {
  if (amount === null || amount === undefined) return '—'
  const n = Number(amount)
  if (Number.isNaN(n)) return String(amount)
  return `${currency} ${n.toFixed(2)}`
}

function Item({ item, currency }) {
  return (
    <li className="itin-item">
      <div className="itin-item-main">
        <span className="itin-item-title">{item.title}</span>
        {item.description ? (
          <span className="itin-item-desc">{item.description}</span>
        ) : null}
        {item.start_time || item.end_time ? (
          <span className="itin-item-time">
            {item.start_time}
            {item.end_time ? ` – ${item.end_time}` : ''}
          </span>
        ) : null}
      </div>
      <span className="itin-item-cost">
        {money(item.estimated_cost, item.currency || currency)}
      </span>
    </li>
  )
}

function Section({ title, items, currency }) {
  if (!items || items.length === 0) return null
  return (
    <div className="itin-section">
      <h4>{title}</h4>
      <ul className="itin-list">
        {items.map((item, i) => (
          <Item key={i} item={item} currency={currency} />
        ))}
      </ul>
    </div>
  )
}

export default function ItineraryView({ itinerary }) {
  if (!itinerary) return null
  const plan = itinerary.plan || {}
  const currency = plan.currency || itinerary.currency || 'USD'
  const budget = plan.budget_analysis
  const days = plan.days || []

  return (
    <div className="itinerary">
      {plan.summary ? <p className="itin-summary">{plan.summary}</p> : null}

      <div className="itin-total-row">
        <span>Estimated total</span>
        <strong>{money(plan.total_estimated_cost ?? itinerary.total_estimated_cost, currency)}</strong>
      </div>

      {budget ? (
        <div
          className={`budget-card ${
            budget.within_budget === false ? 'over' : budget.within_budget ? 'under' : 'neutral'
          }`}
        >
          <div className="budget-head">
            <span className="budget-badge">
              {budget.within_budget === false
                ? 'Over budget'
                : budget.within_budget
                  ? 'Within budget'
                  : 'No budget set'}
            </span>
            {budget.budget != null ? (
              <span>Budget: {money(budget.budget, currency)}</span>
            ) : null}
            {budget.delta != null ? (
              <span>
                {budget.delta >= 0 ? 'Remaining' : 'Shortfall'}:{' '}
                {money(Math.abs(budget.delta), currency)}
              </span>
            ) : null}
          </div>
          {budget.suggestions && budget.suggestions.length > 0 ? (
            <ul className="budget-suggestions">
              {budget.suggestions.map((s, i) => (
                <li key={i}>{s}</li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}

      <Section title="✈️ Flights" items={plan.flights} currency={currency} />
      <Section title="🏨 Accommodation" items={plan.accommodation} currency={currency} />
      <Section title="🎟️ Activities" items={plan.activities} currency={currency} />

      {days.length > 0 ? (
        <div className="itin-section">
          <h4>🗓️ Day by day</h4>
          {days.map((day, i) => (
            <div key={i} className="itin-day">
              <div className="itin-day-head">
                <strong>Day {day.day}</strong>
                {day.date ? <span>{day.date}</span> : null}
                {day.title ? <span className="itin-day-title">{day.title}</span> : null}
              </div>
              <ul className="itin-list">
                {(day.items || []).map((item, j) => (
                  <Item key={j} item={item} currency={currency} />
                ))}
              </ul>
            </div>
          ))}
        </div>
      ) : null}

      {itinerary.provider || itinerary.created_at ? (
        <p className="itin-meta">
          {itinerary.provider ? `Generated by ${itinerary.provider}` : ''}
          {itinerary.model_used ? ` (${itinerary.model_used})` : ''}
          {itinerary.created_at ? ` · ${new Date(itinerary.created_at).toLocaleString()}` : ''}
        </p>
      ) : null}
    </div>
  )
}
