apiVersion: v1
kind: Secret
metadata:
  name: travel-planner-secret
  namespace: travel-planner
type: Opaque
data:
  POSTGRES_USER: dHJhdmVs
  POSTGRES_PASSWORD: UGRTQVRIbzBndg==
  POSTGRES_DB: dHJhdmVs

stringData:
  SECRET_KEY: "dev-secret-change-me"
  JWT_SECRET_KEY: "dev-jwt-secret-change-me"
  INTERNAL_API_TOKEN: "dev-internal-token"
  OPENAI_API_KEY: ""