apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    {{- include "tp.labels" . | nindent 4 }}
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
