{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: trip-service-secrets
  labels:
    {{- include "tp.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  INTERNAL_API_TOKEN: {{ .Values.secrets.internalApiToken | quote }}
  DATABASE_URL: {{ include "tp.databaseUrl" . | quote }}
{{- end }}
