apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: trip-service
    app.kubernetes.io/name: travel-planner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm

spec:
  replicas: 1

  selector:
    matchLabels:
      app: trip-service

  template:
    metadata:
      labels:
        app: trip-service
        app.kubernetes.io/name: travel-planner
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101

      # ------------------------------------------------------------
      # Database migration
      # ------------------------------------------------------------
      initContainers:
        - name: migrate
          image: {{ include "tp.image" (dict "root" . "repo" .Values.tripService.repository) }}
          imagePullPolicy: Never

          command:
            - sh
            - -c
            - |
              until flask db upgrade; do
                echo "waiting for db..."
                sleep 3
              done

          envFrom:
            - configMapRef:
                name: trip-service-config
            - secretRef:
                name: trip-service-secrets

          env:
            - name: POSTGRES_HOST
              value: "postgres"

            - name: POSTGRES_PORT
              value: "5432"

      # ------------------------------------------------------------
      # Trip Service
      # ------------------------------------------------------------
      containers:
        - name: trip-service
          image: {{ include "tp.image" (dict "root" . "repo" .Values.tripService.repository) }}
          imagePullPolicy: Never

          ports:
            - name: http
              containerPort: 5001

          envFrom:
            - configMapRef:
                name: trip-service-config
            - secretRef:
                name: {{ include "tp.secretName" . }}

          env:
            - name: POSTGRES_HOST
              value: "postgres"

            - name: POSTGRES_PORT
              value: "5432"

          readinessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"